- name: Playbook Install ALL
  hosts: all
  become: yes
  vars:
    temp_dir: /home/vlad/temp
  roles:
#    - system_settings
#    - disks_settings
    - set_downloader_for_terraform_and_others
    - install_terraform
    - install_terraform_providers
    - libvirt_settings
#    - get_the_project_dir_ready
#   - delete_temp
