---
# tasks file for install_terraform_providers

  - name: Create directory for terraform provider
    file:
      path: "{{ path_provider_libvirt }}"
      state: directory

  - name: Download provider libvirt from google drive
    command: "python3 {{ temp_dir }}/google/gdrivedl.py {{ download_terraform_provider_libvirt }}"
    args:
      chdir: "{{ temp_dir }}"

  - name: Remove old terraform-provider-libvirt
    file: 
      path: "{{ path_provider_libvirt }}/terraform-provider-libvirt"
      state: absent

  - name: Copy terraform-provider-libvirt from temp to the right place
    copy: 
      remote_src: True 
      src: "{{ temp_dir }}/terraform-provider-libvirt"
      dest: "{{ path_provider_libvirt }}/terraform-provider-libvirt" 
      mode: +x

