---
# tasks file for get_the_project_dir_ready

  - name: Create dir for a project
    file:
      path: "{{ projects_terraform_dir }}"
      state: directory

  - name: Templates for terraform
    template:
      src: "{{ item }}"
      dest: "{{ projects_terraform_dir }}"
    
    loop:
      - templates/libvirt.tf
      - templates/main.tf

  - name: Download images
    get_url:
      url: "{{ item }}"
      dest: "{{ projects_terraform_dir }}"
      setype: https
    loop:
      - "{{ download_images[0] }}"
      - "{{ download_images[1] }}"

  - name: copy id_rsa.pub
    template:
      src: templates/id_rsa.pub
      dest: "{{ temp_dir }}/id_rsa.pub"

  - name: Prepare images set password, uninstall sshd, intall sshd, add ssh key, truncate machine-id
    command: "{{ item }}"
    args:
      chdir: "{{ projects_terraform_dir }}"

    loop:
      - "virt-customize -a {{ projects_terraform_dir }}/{{image_names[0]}} --root-password password:root"
      - "virt-customize -a {{ projects_terraform_dir }}/{{image_names[1]}} --root-password password:root"
      - "virt-customize -a {{ projects_terraform_dir }}/{{image_names[1]}} --uninstall openssh-server"
      - "virt-customize -a {{ projects_terraform_dir }}/{{image_names[1]}} --install openssh-server"
      - "virt-customize -a {{ projects_terraform_dir }}/{{image_names[0]}} --ssh-inject root:file:{{ temp_dir }}/id_rsa.pub"
      - "virt-customize -a {{ projects_terraform_dir }}/{{image_names[1]}} --ssh-inject root:file:{{ temp_dir }}/id_rsa.pub"
      - "virt-customize -a {{ projects_terraform_dir }}/{{image_names[0]}} --truncate /etc/machine-id"
      - "virt-customize -a {{ projects_terraform_dir }}/{{image_names[1]}} --truncate /etc/machine-id"

