---
# tasks file for install_terraform

  - name: Install for terraform
    apt:
      pkg: "{{ packagesForTerraform }}"

  - name: Download terraform from google drive
    command: "python3 {{ temp_dir }}/google/gdrivedl.py {{ download_terraform }}"
    args:
      chdir: "{{ temp_dir }}"

  - name: Unzip terraform
    ansible.builtin.unarchive:
      src: "{{ temp_dir }}/{{ terraform_version_zip }}"
      dest: "{{ terraform_path }}"
      remote_src: yes
      mode: +x


  - name: Edit terraformrc
    template:
      src: templates/.terraformrc
      dest: /root/.terraformrc

